# Generated by Django 4.2.6 on 2023-11-05 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('VIN', models.CharField(max_length=100)),
                ('title_code', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('engine_displacement', models.FloatField(blank=True, null=True)),
                ('cylinders', models.IntegerField(blank=True)),
                ('transmission', models.CharField(blank=True, max_length=100)),
                ('drive_type', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=100)),
                ('keys', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField()),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('reserve_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('vehicle_location', models.TextField()),
                ('sale_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image_1', models.ImageField(blank=True, upload_to='cars')),
                ('image_2', models.ImageField(blank=True, upload_to='cars')),
                ('image_3', models.ImageField(blank=True, upload_to='cars')),
                ('image_4', models.ImageField(blank=True, upload_to='cars')),
                ('image_5', models.ImageField(blank=True, upload_to='cars')),
                ('image_6', models.ImageField(blank=True, upload_to='cars')),
                ('image_7', models.ImageField(blank=True, upload_to='cars')),
                ('image_8', models.ImageField(blank=True, upload_to='cars')),
                ('image_9', models.ImageField(blank=True, upload_to='cars')),
                ('image_10', models.ImageField(blank=True, upload_to='cars')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_date', models.DateTimeField(auto_now=True)),
                ('bid_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplicarbackend.car')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
