# Generated by Django 4.2.6 on 2023-11-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drivers_license',
            field=models.ImageField(blank=True, null=True, upload_to='drivers_licenses/'),
        ),
    ]
