# Generated by Django 4.2.6 on 2023-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0002_car_title_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
