# Generated by Django 4.2.6 on 2023-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0002_car_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='vin',
            new_name='VIN',
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='lot_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='sale_info',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
