# Generated by Django 4.2.6 on 2023-11-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0003_savedvehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='auction',
            field=models.CharField(choices=[('SAA', 'SAA'), ('COPART', 'COPART'), ('IAA', 'IAA')], default='SAA', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='image_10_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_2_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_3_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_4_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_5_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_6_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_7_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_8_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_9_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_auction_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.CharField(blank=True, default=0.0, max_length=100),
        ),
    ]
