# Generated by Django 4.2.6 on 2023-12-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0003_vehiclefilter_damagefields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclefilter',
            name='odometer_brand',
            field=models.CharField(blank=True, choices=[('ACTUAL', 'ACTUAL'), ('EXEMPT', 'EXEMPT'), ('NOT ACTUAL', 'NOT ACTUAL'), ('INOPERABLE', 'INOPERABLE'), ('OTHER', 'OTHER')], max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclefilter',
            name='title_classification',
            field=models.CharField(choices=[('CLEAN', 'CLEAN'), ('SALVAGE', 'SALVAGE'), ('REBUILT', 'REBUILT'), ('EXPORT ONLY', 'EXPORT ONLY'), ('PARTS ONLY', 'PARTS ONLY'), ('OTHER', 'OTHER')], default='CLEAN', max_length=100),
        ),
    ]
