# Generated by Django 4.2.6 on 2023-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0004_vehiclefilter_odometer_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='airbags_deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='grille_damage',
            field=models.BooleanField(default=False),
        ),
    ]
