# Generated by Django 4.2.6 on 2023-12-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0005_car_airbags_deployed_car_grille_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='all_over_damage',
            field=models.BooleanField(default=False),
        ),
    ]
