# Generated by Django 4.2.6 on 2023-12-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplicarbackend', '0006_car_all_over_damage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='bumper_damage',
            new_name='deck_lid_damage',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='trunk_damage',
            new_name='front_bumper_damage',
        ),
        migrations.AddField(
            model_name='car',
            name='hatch_damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='radiator_support_damage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='tailgate_damage',
            field=models.BooleanField(default=False),
        ),
    ]
